### ISSUE TITLE
AdapterDelegatesManager  getItemViewType抛出异常是什么原因

### ISSUE THREAD

**Issue by Seawn** [xuehuayous/DelegationAdapter#19]
2021-01-19 19:52:58.645 30541-30541/com.snail.card E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.snail.card, PID: 30541
    java.lang.NullPointerException: No AdapterDelegate added that matches position = 3 item = com.snail.card.recommend.entity.RecommendInfo$Data@fdcd028 in data source.
        at com.kevin.delegationadapter.AdapterDelegatesManager.getItemViewType(AdapterDelegatesManager.kt:130)
        at com.kevin.delegationadapter.AbsDelegationAdapter.getItemViewType(AbsDelegationAdapter.kt:75)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6186)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:22160)
        at android.view.ViewGroup.layout(ViewGroup.java:6402)
        at com.andview.refreshview.XRefreshView.onLayout(XRefreshView.java:365)
        at android.view.View.layout(View.java:22160)
        at android.view.ViewGroup.layout(ViewGroup.java:6402)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22160)
        at android.view.ViewGroup.layout(ViewGroup.java:6402)
        at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
        at android.view.View.layout(View.java:22160)
        at android.view.ViewGroup.layout(ViewGroup.java:6402)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:22160)
        at android.view.ViewGroup.layout(ViewGroup.java:6402)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22160)
        at android.view.ViewGroup.layout(ViewGroup.java:6402)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22160)
        at android.view.ViewGroup.layout(ViewGroup.java:6402)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:810)
        at android.view.View.layout(View.java:22160)
        at android.view.ViewGroup.layout(ViewGroup.java:6402)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3330)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2826)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1901)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8066)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
        at android.view.Choreographer.doCallbacks(Choreographer.java:860)
        at android.view.Choreographer.doFrame(Choreographer.java:785)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
2021-01-19 19:52:58.646 30541-30541/com.snail.card E/AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
2021-01-19 19:52:58.676 30541-30541/com.snail.card I/Process: Sending signal. PID: 30541 SIG: 9

**Comment by xuehuayous** [comment]
是你没有添加处理对应数据类型的AdapterDelegate，会根据数据的类型去找能处理该类型数据的AdapterDelegate，如果找不到就会报错。

**Comment by Seawn** [comment]
哦明白了，后台多返回了一个没有用到的类型，感谢
